### ISSUE TITLE
http://shinken.io/grab/booster-nrpe 500 error

### ISSUE THREAD

**Issue by gak** [shinken-solutions/shinken.io#10]
I was installing the shinken_thruk_graphite Docker image and discovered the server is returning an error.

The actual command run from the Dockerfile (presumably):
```
shinken install booster-nrpe
```

The error on the server:
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://shinken.io/grab/booster-nrpe' caused an error:

Internal Server Error
Exception:

Exception(u'Cannot find the file gst/packages/booster-nrpe/booster-nrpe.tar.gz',)
Traceback:

Traceback (most recent call last):
  File "/opt/shinken.io/wsgi/../webgears/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/opt/shinken.io/wsgi/../webgears/bottle.py", line 1572, in wrapper
    rv = callback(*a, **ka)
  File "/opt/shinken.io/wsgi/../shinkenio/pages/package/package.py", line 29, in grab
    return app.grab_package(pname)
  File "/opt/shinken.io/wsgi/../shinkenio/shinkenio.py", line 272, in grab_package
    raise Exception("Cannot find the file %s" % tar_gz_path)
Exception: Cannot find the file gst/packages/booster-nrpe/booster-nrpe.tar.gz
```

**Comment by david-guenault** [comment]
Confirmed. As a workaround you can grab the github repo and install it
locally

enter your container and the do:

```
git clone https://github.com/shinken-monitoring/mod-booster-nrpe
shinken install --local mod-booster-nrpe
```

@gst coold you please push the module ?



2015-04-27 6:52 GMT+02:00 Gerald Kaszuba <notifications@github.com>:

**Comment by gak** [comment]
Thanks :tada:

**Comment by david-guenault** [comment]
btw you are talking about this container ? https://registry.hub.docker.com/u/rohit01/shinken_thruk_graphite/

**Comment by gak** [comment]
Yes, I presume that's it, although I didn't use the image from Docker Hub Registry.

I specifically built from the repo, and ran a ```docker build``` on it:
https://github.com/rohit01/docker_shinken/tree/master/shinken_thruk_graphite

**Comment by david-guenault** [comment]
ok thx.

**Comment by naparuba** [comment]
I give a look to shinken.io

**Comment by naparuba** [comment]
Fixed :) was my fault on a server operation during the package ownership transfert to gst :)

**Comment by gak** [comment]
Thanks for the quick response and fix. :smile:
